# Generated by Django 5.0.8 on 2024-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_product_ordered_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applied_offer_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='applied_offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
