# Generated by Django 5.0.8 on 2024-10-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_offer_added'),
        ('store', '0022_remove_product_ordered_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.offer'),
        ),
    ]
