# Generated by Django 5.0.8 on 2024-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_applied_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='applied_offer_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
