# Generated by Django 5.0.8 on 2024-10-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_applied_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='applied_offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
