# Generated by Django 5.0.8 on 2024-10-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_order_coupon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_name',
        ),
    ]
